'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

interface Job { id:string; status:string; mode:string; created_at:string; display_strategy_id?:string; user_strategy_id?:string; strategy_code?:string; strategy_id?:string; timeframe?:string; }
function fmt(n:any,d=2){const x=Number(n??0);return Number.isFinite(x)?x.toFixed(d).replace(/\.00$/,''):'0'}
function displayStrategy(j:Job){return j.display_strategy_id||j.user_strategy_id||j.strategy_code||j.strategy_id||'STRATEGY'}
function coachJobLabel(j:Job){const date=j.created_at?new Date(j.created_at).toLocaleString(undefined,{hour12:false}):'date unknown';return `${displayStrategy(j)} · ${(j.mode||'job').toUpperCase()} · ${j.status} · ${date}`}
function ddCurve(curve:number[]){let peak=curve[0]||0;return curve.map((v,i)=>{peak=Math.max(peak,v);return{trade:i+1,drawdown:Number((v-peak).toFixed(3))}})}
function rDist(rs:number[]){const rows=[{name:'Big Loss',trades:0},{name:'Small Loss',trades:0},{name:'Flat',trades:0},{name:'Good Win',trades:0},{name:'Big Win',trades:0}];rs.forEach(r=>{if(r<=-1)rows[0].trades++;else if(r<0)rows[1].trades++;else if(r<0.5)rows[2].trades++;else if(r<2)rows[3].trades++;else rows[4].trades++});return rows}
function rolling(rs:number[],w=20){return rs.map((_,i)=>{const s=rs.slice(Math.max(0,i-w+1),i+1);return{trade:i+1,avg:Number((s.reduce((a,b)=>a+b,0)/Math.max(1,s.length)).toFixed(3))}})}
function score(m:any,wf:any,stress:any,mc:any){let s=50;if(Number(m.avg_R)>0)s+=15;if(Number(m.profit_factor)>1.2)s+=12;if(Number(m.max_drawdown_R)>-10)s+=8;if(wf.status==='PASS')s+=8;if(stress.status==='ROBUST')s+=5;if(Number(mc.risk_of_ruin_minus_10R||0)>0.1)s-=15;return Math.max(0,Math.min(100,Math.round(s)))}
function executive(m:any,confidence:number){const avg=Number(m.avg_R||0),pf=Number(m.profit_factor||0),wr=Number(m.win_rate||0)*100,dd=Number(m.max_drawdown_R||0);if(confidence>=75)return `This is a promising paper system. Expectancy is ${fmt(avg,3)}R/trade, profit factor is ${fmt(pf)}, win rate is ${fmt(wr,1)}%, and drawdown is ${fmt(dd)}R. Your next job is validation, not random optimization.`;if(confidence>=55)return `This system is useful but not proven. Expectancy is ${fmt(avg,3)}R/trade with profit factor ${fmt(pf)}. Continue testing, isolate weak regimes, and avoid increasing risk until stability improves.`;return `This system is not ready to scale. Expectancy, drawdown, or robustness are not strong enough. Your next work is filtering weak trades and reducing loss clusters.`}
function roadmap(m:any,wf:any,stress:any,rs:number[]){const avg=Number(m.avg_R||0),pf=Number(m.profit_factor||0);const steps=['Run the same rule set on a fresh out-of-sample period.','Tag trades by setup quality, regime, and symbol before changing parameters.'];if(avg<=0||pf<1)steps.unshift('Reduce low-quality entries first; do not increase risk or add symbols yet.');if(wf.status!=='PASS')steps.push('Improve walk-forward stability before trusting this strategy.');if(stress.status!=='ROBUST')steps.push('Stress-test wider slippage, worse fills, and weaker market conditions.');if(rs.length<100)steps.push('Collect at least 100 closed trades before making a scaling decision.');return steps}
function tradeReview(rs:number[]){if(!rs.length)return['No closed trades available yet.'];const worst=[...rs].map((r,i)=>({trade:i+1,r})).sort((a,b)=>a.r-b.r).slice(0,3);const best=[...rs].map((r,i)=>({trade:i+1,r})).sort((a,b)=>b.r-a.r).slice(0,3);return[`Best trades: ${best.map(x=>`#${x.trade} (${fmt(x.r,2)}R)`).join(', ')||'none'}.`,`Worst trades: ${worst.map(x=>`#${x.trade} (${fmt(x.r,2)}R)`).join(', ')||'none'}.`,'Review whether worst trades share the same regime, time window, or setup score pattern.']}
function phases(rs:number[]){const size=Math.max(1,Math.ceil((rs.length||1)/4));return[0,1,2,3].map(i=>{const s=rs.slice(i*size,(i+1)*size);return{name:`Block ${i+1}`,r:Number(s.reduce((a,b)=>a+b,0).toFixed(2))}})}
function Card({label,value,sub,accent}:{label:string;value:any;sub?:string;accent?:string}){return <div style={{background:'#111827',border:'1px solid #334155',borderRadius:14,padding:'20px 24px'}}><div style={{fontSize:11,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:8}}>{label}</div><div style={{fontSize:30,fontWeight:900,color:accent||'#e2e8f0'}}>{value}</div>{sub&&<div style={{fontSize:12,color:'#94a3b8',marginTop:6}}>{sub}</div>}</div>}
function List({title,items,accent}:{title:string;items?:string[];accent?:string}){return <div style={{background:'#111827',border:'1px solid #334155',borderRadius:14,padding:22}}><h3 style={{marginTop:0}}>{title}</h3>{items?.length?items.map((x,i)=><div key={i} style={{padding:'9px 0',borderBottom:'1px solid #1e293b',color:accent||'#cbd5e1',lineHeight:1.5}}>• {x}</div>):<p style={{color:'#94a3b8'}}>No items available yet.</p>}</div>}
function Chart({title,children}:{title:string;children:any}){return <div style={{background:'#111827',border:'1px solid #334155',borderRadius:16,padding:24,marginBottom:20}}><div style={{fontSize:13,color:'#c4b5fd',textTransform:'uppercase',letterSpacing:1,marginBottom:16,fontWeight:800}}>{title}</div>{children}</div>}

export default function QuantCoach(){
 const[jobs,setJobs]=useState<Job[]>([]),[report,setReport]=useState<any>(null),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{api('/jobs/').then((r:any)=>{setJobs(Array.isArray(r)?r:(r.jobs||[]));setMsg('')}).catch(e=>setMsg('Cannot reach QuantOS API. Start the backend and refresh. Details: '+e.message))},[]);
 async function load(id:string){if(!id)return;setMsg('');setReport(null);setLoading(true);try{setReport(await api(`/coach/${id}/coach-report`))}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 const m=report?.metrics||{},mc=report?.monte_carlo||{},fit=report?.lifestyle_fit||{},discipline=report?.rule_discipline||{},stress=report?.stress_testing||{},wf=report?.walk_forward_analysis||{},llm=report?.llm_coach||{};
 const curve:number[]=Array.isArray(m.equity_curve_R)?m.equity_curve_R.map((x:any)=>Number(x||0)):[];
 const rs:number[]=curve.map((v,i)=>i===0?v:v-curve[i-1]);
 const hasData=Number(m.trades||report?.summary?.total_trades||0)>0;
 const equity=curve.map((v,i)=>({trade:i+1,equity:Number(v.toFixed(3))}));const dd=useMemo(()=>ddCurve(curve),[report]);const conf=score(m,wf,stress,mc);const tip={background:'#111827',border:'1px solid #475569',color:'#e2e8f0'};
 const s={page:{background:'#0d0d1a',minHeight:'100vh',padding:24,fontFamily:'system-ui,sans-serif',color:'#e2e8f0'},h1:{fontSize:30,fontWeight:900,margin:0,background:'linear-gradient(135deg,#6366f1,#8b5cf6)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'},sub:{color:'#bad4ff',marginTop:8,fontSize:14,lineHeight:1.6},card:{background:'#111827',border:'1px solid #334155',borderRadius:16,padding:24,marginBottom:20},title:{fontSize:13,color:'#c4b5fd',textTransform:'uppercase' as const,letterSpacing:1,marginBottom:16,fontWeight:800},grid2:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(390px,1fr))',gap:18,marginBottom:20},grid3:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:18,marginBottom:20},select:{width:'100%',background:'#0d0d1a',color:'#e2e8f0',border:'1px solid #475569',borderRadius:10,padding:'12px 14px',fontSize:14},danger:{background:'#2a1a1a',border:'1px solid #ef444433',borderRadius:8,padding:'12px 16px',color:'#fca5a5',marginBottom:16}};
 return <div style={s.page}><div style={{marginBottom:28}}><h1 style={s.h1}>Quant Coach v3</h1><p style={s.sub}>Real-data coaching report with executive summary, confidence score, risk breakdown, roadmap, trade review, and rule-discipline guidance.</p></div>{msg&&<div style={s.danger}>{msg}</div>}
  <div style={s.card}><div style={s.title}>Select Completed Job</div><select style={s.select} onChange={e=>load(e.target.value)} defaultValue=""><option value="">Choose a completed backtest or paper job…</option>{jobs.filter(j=>j.status==='completed').map(j=><option key={j.id} value={j.id}>{coachJobLabel(j)}</option>)}</select>{loading&&<div style={{marginTop:12,color:'#a78bfa'}}>Generating report…</div>}</div>
  {report&&!hasData&&<div style={s.card}><div style={s.title}>Coach Status</div><h2 style={{marginTop:0,color:'#f59e0b'}}>Waiting for completed trades</h2><p style={{color:'#cbd5e1',lineHeight:1.6}}>Run a backtest/live paper session until closed trades exist, then reopen this report.</p></div>}
  {report&&hasData&&<><div style={s.grid3}><Card label="Confidence" value={`${conf}/100`} sub="Rule-engine quality score" accent={conf>=75?'#22c55e':conf>=55?'#f59e0b':'#ef4444'}/><Card label="Expectancy" value={`${fmt(m.avg_R,3)}R`} sub={`${m.trades??0} trades`} accent={(m.avg_R||0)>0?'#22c55e':'#ef4444'}/><Card label="Max Drawdown" value={`${fmt(m.max_drawdown_R)}R`} sub="Worst observed" accent="#f59e0b"/></div>
   <div style={s.card}><div style={s.title}>Executive Summary</div><p style={{color:'#dbeafe',fontSize:16,lineHeight:1.75,margin:0}}>{llm.narrative||executive(m,conf)}</p><p style={{color:'#94a3b8',fontSize:12,marginTop:12}}>LLM status: {llm.status||'rule-engine narrative active'} · Research only, not financial advice.</p></div>
   <div style={s.grid2}><List title="Strengths" items={llm.strengths||report.coach_insights}/><List title="Risks / Weaknesses" items={llm.risks||report.weaknesses||[`Drawdown: ${fmt(m.max_drawdown_R)}R`,`Profit factor: ${fmt(m.profit_factor)}`]} accent="#fca5a5"/><List title="Next 30 Trades Roadmap" items={llm.next_steps||roadmap(m,wf,stress,rs)} accent="#a78bfa"/><List title="Trade Review Focus" items={tradeReview(rs)} accent="#93c5fd"/></div>
   <div style={s.grid2}><Chart title="Equity Curve"><ResponsiveContainer width="100%" height={250}><AreaChart data={equity}><CartesianGrid strokeDasharray="3 3" stroke="#334155"/><XAxis dataKey="trade" stroke="#cbd5e1"/><YAxis stroke="#cbd5e1"/><Tooltip contentStyle={tip}/><Area type="monotone" dataKey="equity" stroke="#38bdf8" fill="#38bdf855" strokeWidth={3}/></AreaChart></ResponsiveContainer></Chart><Chart title="Drawdown Curve"><ResponsiveContainer width="100%" height={250}><AreaChart data={dd}><CartesianGrid strokeDasharray="3 3" stroke="#334155"/><XAxis dataKey="trade" stroke="#cbd5e1"/><YAxis stroke="#cbd5e1"/><Tooltip contentStyle={tip}/><Area type="monotone" dataKey="drawdown" stroke="#f59e0b" fill="#f59e0b44" strokeWidth={3}/></AreaChart></ResponsiveContainer></Chart><Chart title="Rolling Expectancy"><ResponsiveContainer width="100%" height={250}><LineChart data={rolling(rs)}><CartesianGrid strokeDasharray="3 3" stroke="#334155"/><XAxis dataKey="trade" stroke="#cbd5e1"/><YAxis stroke="#cbd5e1"/><Tooltip contentStyle={tip}/><Line type="monotone" dataKey="avg" stroke="#22c55e" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Chart><Chart title="R Distribution"><ResponsiveContainer width="100%" height={250}><BarChart data={rDist(rs)}><CartesianGrid strokeDasharray="3 3" stroke="#334155"/><XAxis dataKey="name" stroke="#cbd5e1"/><YAxis stroke="#cbd5e1"/><Tooltip contentStyle={tip}/><Bar dataKey="trades" fill="#a78bfa" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Win/Loss Mix"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={[{name:'Wins',value:Math.round(Number(m.win_rate||0)*Number(m.trades||0))},{name:'Losses',value:Math.max(0,Number(m.trades||0)-Math.round(Number(m.win_rate||0)*Number(m.trades||0)))}].filter(x=>x.value>0)} dataKey="value" nameKey="name" outerRadius={90} label>{[0,1].map((_,i)=><Cell key={i} fill={i===0?'#22c55e':'#ef4444'}/>)}</Pie><Tooltip contentStyle={tip}/></PieChart></ResponsiveContainer></Chart><Chart title="Sample Progression"><ResponsiveContainer width="100%" height={250}><BarChart data={phases(rs)}><CartesianGrid strokeDasharray="3 3" stroke="#334155"/><XAxis dataKey="name" stroke="#cbd5e1"/><YAxis stroke="#cbd5e1"/><Tooltip contentStyle={tip}/><Bar dataKey="r" fill="#38bdf8" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Chart></div>
   <div style={s.grid2}><List title="Rule Discipline" items={[`Manual violations: ${discipline.manual_rule_violations_detected??0}`,`R impact: ${discipline.manual_rule_violation_R_impact??0}R`,`Tracking status: ${discipline.status||'unknown'}`]}/><List title="Lifestyle Fit" items={[`Score: ${fit.score??'—'}/100`,`Label: ${fit.label||'—'}`,`Monitoring burden: ${fit.monitoring_burden||'—'}`,`Psychological burden: ${fit.psychological_burden||'—'}`]}/></div>
  </>}<div style={{color:'#94a3b8',fontSize:11,textAlign:'center',padding:'16px 0',marginTop:24,borderTop:'1px solid #334155'}}>QuantOS Quant Coach is research/analytics only. Paper trading and backtests are hypothetical. Not financial advice.</div></div>
}
