"""Local engine token and heartbeat bridge.

The cloud API never receives exchange API secrets. A user-local engine posts only
safe telemetry/events with a short-lived engine token generated by the account.
"""
from __future__ import annotations

import hashlib
import secrets
import time
from typing import Any

from app.db import get_conn, now, row_to_dict
from app.core.config import settings

TOKEN_TTL_SECONDS = 60 * 60 * 12


def _p() -> str:
    return "%s" if settings.is_postgres() else "?"


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def ensure_schema() -> None:
    with get_conn() as conn:
        if settings.is_postgres():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS engine_tokens (
                    token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, mode TEXT NOT NULL,
                    exchange TEXT NOT NULL, source TEXT NOT NULL, engine_version TEXT,
                    expires_at REAL NOT NULL, created_at TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS engine_heartbeats (
                    user_id TEXT PRIMARY KEY, mode TEXT, exchange TEXT, source TEXT,
                    engine_version TEXT, connected INTEGER NOT NULL DEFAULT 0,
                    p50_latency_us REAL DEFAULT 0, p95_latency_us REAL DEFAULT 0, p99_latency_us REAL DEFAULT 0,
                    latest_price REAL DEFAULT 0, last_heartbeat TEXT NOT NULL, payload_json TEXT
                )
                """
            )
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS engine_tokens (
                    token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, mode TEXT NOT NULL,
                    exchange TEXT NOT NULL, source TEXT NOT NULL, engine_version TEXT,
                    expires_at REAL NOT NULL, created_at TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS engine_heartbeats (
                    user_id TEXT PRIMARY KEY, mode TEXT, exchange TEXT, source TEXT,
                    engine_version TEXT, connected INTEGER NOT NULL DEFAULT 0,
                    p50_latency_us REAL DEFAULT 0, p95_latency_us REAL DEFAULT 0, p99_latency_us REAL DEFAULT 0,
                    latest_price REAL DEFAULT 0, last_heartbeat TEXT NOT NULL, payload_json TEXT
                )
                """
            )
        conn.commit()


def create_engine_token(user_id: str, mode: str = "paper", exchange: str = "binance", source: str = "BTCUSDT") -> dict[str, Any]:
    ensure_schema()
    token = "qeng_" + secrets.token_urlsafe(32)
    expires_at = time.time() + TOKEN_TTL_SECONDS
    with get_conn() as conn:
        conn.execute(
            f"INSERT INTO engine_tokens(token_hash,user_id,mode,exchange,source,expires_at,created_at,revoked) VALUES({_p()},{_p()},{_p()},{_p()},{_p()},{_p()},{_p()},0)",
            (_hash_token(token), user_id, mode[:32], exchange[:64], source[:128], expires_at, now()),
        )
        conn.commit()
    return {
        "token": token,
        "expires_at_epoch": int(expires_at),
        "command": f"build\\Release\\quantos-engine.exe --token {token} --mode {mode} --exchange {exchange} --symbol {source}",
        "windows_command": f"build\\Release\\quantos-engine.exe --token {token} --mode {mode} --exchange {exchange} --symbol {source}",
        "linux_command": f"./build/quantos-engine --token {token} --mode {mode} --exchange {exchange} --symbol {source}",
        "safe_mode": True,
    }


def resolve_token(token: str) -> dict[str, Any] | None:
    ensure_schema()
    with get_conn() as conn:
        row = conn.execute(
            f"SELECT * FROM engine_tokens WHERE token_hash={_p()} AND revoked=0",
            (_hash_token(token),),
        ).fetchone()
    data = row_to_dict(row) if row else {}
    if not data or float(data.get("expires_at") or 0) < time.time():
        return None
    return data


def record_heartbeat(token: str, payload: dict[str, Any]) -> dict[str, Any]:
    import json
    token_row = resolve_token(token)
    if not token_row:
        raise ValueError("Invalid or expired engine token")
    user_id = str(token_row["user_id"])
    safe_payload = {
        k: payload.get(k)
        for k in ["symbol", "event", "candles", "orders", "trades", "positions", "pnl", "risk", "logs"]
        if k in payload
    }
    p50 = float(payload.get("p50_latency_us") or payload.get("p50") or 0)
    p95 = float(payload.get("p95_latency_us") or payload.get("p95") or 0)
    p99 = float(payload.get("p99_latency_us") or payload.get("p99") or 0)
    latest = float(payload.get("latest_price") or payload.get("price") or 0)
    heartbeat_at = now()
    with get_conn() as conn:
        conn.execute(
            f"""
            INSERT INTO engine_heartbeats(user_id,mode,exchange,source,engine_version,connected,p50_latency_us,p95_latency_us,p99_latency_us,latest_price,last_heartbeat,payload_json)
            VALUES({_p()},{_p()},{_p()},{_p()},{_p()},1,{_p()},{_p()},{_p()},{_p()},{_p()},{_p()})
            ON CONFLICT(user_id) DO UPDATE SET mode=excluded.mode, exchange=excluded.exchange, source=excluded.source,
              engine_version=excluded.engine_version, connected=1, p50_latency_us=excluded.p50_latency_us,
              p95_latency_us=excluded.p95_latency_us, p99_latency_us=excluded.p99_latency_us,
              latest_price=excluded.latest_price, last_heartbeat=excluded.last_heartbeat, payload_json=excluded.payload_json
            """,
            (user_id, str(payload.get("mode") or token_row.get("mode") or "paper")[:32], str(payload.get("exchange") or token_row.get("exchange") or "")[:64], str(payload.get("source") or payload.get("symbol") or token_row.get("source") or "")[:128], str(payload.get("engine_version") or "unknown")[:64], p50, p95, p99, latest, heartbeat_at, json.dumps(safe_payload)[:20000]),
        )
        conn.commit()
    return status_for_user(user_id)


def status_for_user(user_id: str) -> dict[str, Any]:
    ensure_schema()
    with get_conn() as conn:
        row = conn.execute(f"SELECT * FROM engine_heartbeats WHERE user_id={_p()}", (user_id,)).fetchone()
    data = row_to_dict(row) if row else {}
    if not data:
        return {"connected": False, "status": "disconnected"}
    # ISO string sorted enough; let UI show exact value. Mark stale after 30s best-effort.
    return {
        "connected": bool(data.get("connected")),
        "status": "connected" if data.get("connected") else "disconnected",
        "exchange": data.get("exchange"),
        "source": data.get("source"),
        "mode": data.get("mode"),
        "last_heartbeat": data.get("last_heartbeat"),
        "engine_version": data.get("engine_version"),
        "latest_price": data.get("latest_price"),
        "latency": {"p50_us": data.get("p50_latency_us"), "p95_us": data.get("p95_latency_us"), "p99_us": data.get("p99_latency_us")},
        "payload": data.get("payload_json"),
    }
